import '@testing-library/jest-dom';

// Baseline window.clubhouse mock — same shape as the preload bridge (src/preload/index.ts).
// Individual tests can override specific methods via vi.mocked() or vi.spyOn().
//
// IMPORTANT: Keep this in sync with src/preload/index.ts.
// The preload-bridge-sync.test.ts test will catch any drift.

const noop = () => {};
const asyncNoop = async () => {};

vi.stubGlobal('clubhouse', {
  platform: process.platform,
  getPathForFile: (_file: File) => '',
  pty: {
    spawnShell: asyncNoop,
    write: noop,
    resize: noop,
    kill: asyncNoop,
    getBuffer: async () => '',
    onData: () => noop,
    onExit: () => noop,
  },
  project: {
    list: async () => [],
    add: asyncNoop,
    remove: asyncNoop,
    pickDirectory: async () => null,
    checkGit: async () => false,
    gitInit: asyncNoop,
    update: asyncNoop,
    pickIcon: asyncNoop,
    reorder: asyncNoop,
    readIcon: async () => null,
    pickImage: asyncNoop,
    saveCroppedIcon: asyncNoop,
    listClubhouseFiles: async () => [],
    resetProject: async () => false,
  },
  agent: {
    listDurable: async () => [],
    createDurable: asyncNoop,
    deleteDurable: asyncNoop,
    renameDurable: asyncNoop,
    updateDurable: asyncNoop,
    pickIcon: asyncNoop,
    saveIcon: asyncNoop,
    readIcon: async () => null,
    removeIcon: asyncNoop,
    reorderDurable: asyncNoop,
    getWorktreeStatus: asyncNoop,
    deleteCommitPush: asyncNoop,
    deleteCleanupBranch: asyncNoop,
    deleteSavePatch: asyncNoop,
    deleteForce: asyncNoop,
    deleteUnregister: asyncNoop,
    readQuickSummary: async () => null,
    getDurableConfig: asyncNoop,
    updateDurableConfig: asyncNoop,
    spawnAgent: asyncNoop,
    killAgent: asyncNoop,
    getModelOptions: async () => [],
    checkOrchestrator: async () => ({ available: true }),
    getOrchestrators: async () => [],
    getToolVerb: async () => '',
    getSummaryInstruction: async () => '',
    readTranscript: async () => null,
    isHeadlessAgent: async () => false,
    onHookEvent: () => noop,
    // Structured mode
    startStructured: asyncNoop,
    cancelStructured: asyncNoop,
    sendStructuredMessage: asyncNoop,
    respondPermission: asyncNoop,
    onStructuredEvent: () => noop,
    listSessions: async () => [],
    updateSessionName: asyncNoop,
    getTranscriptInfo: asyncNoop,
    readTranscriptPage: asyncNoop,
    readSessionTranscript: async () => null,
    getSessionSummary: async () => null,
  },
  git: {
    info: asyncNoop,
    checkout: asyncNoop,
    stage: asyncNoop,
    unstage: asyncNoop,
    stageAll: asyncNoop,
    unstageAll: asyncNoop,
    discard: asyncNoop,
    commit: asyncNoop,
    push: asyncNoop,
    pull: asyncNoop,
    diff: async () => '',
    createBranch: asyncNoop,
    stash: asyncNoop,
    stashPop: asyncNoop,
  },
  agentSettings: {
    readInstructions: async () => '',
    saveInstructions: asyncNoop,
    readMcpConfig: async () => [],
    listSkills: async () => [],
    listAgentTemplates: async () => [],
    listSourceSkills: async () => [],
    listSourceAgentTemplates: async () => [],
    readSourceSkillContent: async () => '',
    writeSourceSkillContent: asyncNoop,
    deleteSourceSkill: asyncNoop,
    readSourceAgentTemplateContent: async () => '',
    writeSourceAgentTemplateContent: asyncNoop,
    deleteSourceAgentTemplate: asyncNoop,
    createSkill: asyncNoop,
    createAgentTemplate: asyncNoop,
    readPermissions: async () => ({}),
    savePermissions: asyncNoop,
    readSkillContent: async () => '',
    writeSkillContent: asyncNoop,
    deleteSkill: asyncNoop,
    readAgentTemplateContent: async () => '',
    writeAgentTemplateContent: asyncNoop,
    deleteAgentTemplate: asyncNoop,
    listAgentTemplateFiles: async () => [],
    readMcpRawJson: async () => '{"mcpServers": {}}',
    writeMcpRawJson: async () => ({ ok: true }),
    readProjectAgentDefaults: async () => ({}),
    writeProjectAgentDefaults: asyncNoop,
    resetProjectAgentDefaults: asyncNoop,
    getConventions: async () => null,
    materializeAgent: asyncNoop,
    previewMaterialization: async () => null,
    computeConfigDiff: async () => ({ agentId: '', agentName: '', hasDiffs: false, items: [] }),
    propagateConfigChanges: async () => ({ ok: true, message: '', propagatedCount: 0 }),
  },
  file: {
    readTree: async () => [],
    read: async () => '',
    readBinary: async () => '',
    write: asyncNoop,
    showInFolder: asyncNoop,
    mkdir: asyncNoop,
    delete: asyncNoop,
    rename: asyncNoop,
    copy: asyncNoop,
    stat: async () => ({ size: 0, isDirectory: false, isFile: true, modifiedAt: 0 }),
  },
  plugin: {
    discoverCommunity: async () => [],
    storageRead: async () => undefined,
    storageWrite: asyncNoop,
    storageDelete: asyncNoop,
    storageList: async () => [],
    fileRead: async () => '',
    fileWrite: asyncNoop,
    fileDelete: asyncNoop,
    fileExists: async () => false,
    fileListDir: async () => [],
    gitignoreAdd: asyncNoop,
    gitignoreRemove: asyncNoop,
    gitignoreCheck: async () => false,
    startupMarkerRead: async () => null,
    startupMarkerWrite: asyncNoop,
    startupMarkerClear: asyncNoop,
    mkdir: asyncNoop,
    uninstall: asyncNoop,
  },
  marketplace: {
    fetchRegistry: async () => ({ registry: { version: 1, updated: '', plugins: [] }, featured: null }),
    installPlugin: async () => ({ success: true }),
    checkPluginUpdates: async () => [],
    updatePlugin: asyncNoop,
    getPluginUpdatesStatus: () => ({ updates: [], checking: false, lastCheck: null, updating: {}, error: null }),
    onPluginUpdatesChanged: () => noop,
  },
  log: {
    write: noop,
    getSettings: async () => ({ enabled: true, namespaces: {}, retention: 'medium', minLogLevel: 'info' }),
    saveSettings: asyncNoop,
    getNamespaces: async () => [],
    getPath: async () => '',
  },
  process: {
    exec: async () => ({ stdout: '', stderr: '', exitCode: 0 }),
  },
  app: {
    openExternalUrl: asyncNoop,
    getNotificationSettings: async () => ({ enabled: true }),
    saveNotificationSettings: asyncNoop,
    sendNotification: asyncNoop,
    closeNotification: asyncNoop,
    onNotificationClicked: () => noop,
    onOpenSettings: () => noop,
    onOpenAbout: () => noop,
    getTheme: async () => ({ themeId: 'catppuccin-mocha' }),
    saveTheme: asyncNoop,
    updateTitleBarOverlay: asyncNoop,
    getOrchestratorSettings: async () => ({ enabled: ['claude-code'] }),
    saveOrchestratorSettings: asyncNoop,
    getVersion: async () => '0.0.0-test',
    getArchInfo: async () => ({ arch: 'arm64', platform: 'darwin', rosetta: false }),
    getHeadlessSettings: async () => ({ enabled: true }),
    saveHeadlessSettings: asyncNoop,
    setDockBadge: asyncNoop,
    getBadgeSettings: async () => ({ showBadge: true }),
    saveBadgeSettings: asyncNoop,
    getUpdateSettings: async () => ({ autoUpdate: false }),
    saveUpdateSettings: asyncNoop,
    checkForUpdates: asyncNoop,
    getUpdateStatus: async () => ({ state: 'idle' }),
    applyUpdate: asyncNoop,
    getPendingReleaseNotes: async () => null,
    clearPendingReleaseNotes: asyncNoop,
    getVersionHistory: async () => [],
    getClipboardSettings: async () => ({ clipboardCompat: false }),
    saveClipboardSettings: asyncNoop,
    getClubhouseModeSettings: async () => ({ enabled: false }),
    saveClubhouseModeSettings: asyncNoop,
    onUpdateStatusChanged: () => noop,
  },
  profile: {
    getSettings: async () => ({ profiles: [] }),
    saveProfile: asyncNoop,
    deleteProfile: asyncNoop,
    getProfileEnvKeys: async () => [],
  },
  annex: {
    getSettings: async () => ({ enabled: false, deviceName: '' }),
    saveSettings: asyncNoop,
    getStatus: async () => ({ advertising: false, port: 0, pin: '', connectedCount: 0 }),
    regeneratePin: asyncNoop,
    onStatusChanged: () => noop,
  },
  window: {
    createPopout: asyncNoop,
    closePopout: asyncNoop,
    listPopouts: async () => [],
    isPopout: () => false,
    getPopoutParams: () => null,
    focusMain: asyncNoop,
    onNavigateToAgent: () => noop,
    getAgentState: async () => ({ agents: {}, agentDetailedStatus: {}, agentIcons: {} }),
    onRequestAgentState: () => noop,
    respondAgentState: noop,
    getHubState: async () => null,
    onRequestHubState: () => noop,
    respondHubState: noop,
    onHubStateChanged: () => noop,
    broadcastHubState: noop,
    sendHubMutation: noop,
    onHubMutation: () => noop,
  },
});
