import '@testing-library/jest-dom';

// jsdom doesn't have ResizeObserver — provide a no-op polyfill for tests
if (typeof globalThis.ResizeObserver === 'undefined') {
  globalThis.ResizeObserver = class ResizeObserver {
    observe() {}
    unobserve() {}
    disconnect() {}
  } as any;
}

// jsdom doesn't implement scrollIntoView — provide a no-op polyfill
if (typeof Element.prototype.scrollIntoView !== 'function') {
  Element.prototype.scrollIntoView = function () {};
}

// Baseline window.clubhouse mock — same shape as the preload bridge (src/preload/index.ts).
// Individual tests can override specific methods via vi.mocked() or vi.spyOn().
//
// IMPORTANT: Keep this in sync with src/preload/index.ts.
// The preload-bridge-sync.test.ts test will catch any drift.

const noop = () => {};
const asyncNoop = async () => {};

vi.stubGlobal('clubhouse', {
  platform: process.platform,
  getPathForFile: (_file: File) => '',
  settings: {
    get: async () => null,
    save: asyncNoop,
  },
  pty: {
    spawnShell: asyncNoop,
    write: noop,
    resize: noop,
    kill: asyncNoop,
    getBuffer: async () => '',
    onData: () => noop,
    onExit: () => noop,
  },
  project: {
    list: async () => [],
    add: asyncNoop,
    remove: asyncNoop,
    pickDirectory: async () => null,
    checkGit: async () => false,
    gitInit: asyncNoop,
    update: asyncNoop,
    pickIcon: asyncNoop,
    reorder: asyncNoop,
    readIcon: async () => null,
    pickImage: asyncNoop,
    saveCroppedIcon: asyncNoop,
    listClubhouseFiles: async () => [],
    resetProject: async () => false,
    readLaunchWrapper: async () => undefined,
    writeLaunchWrapper: asyncNoop,
    readMcpCatalog: async () => [],
    writeMcpCatalog: asyncNoop,
    readDefaultMcps: async () => [],
    writeDefaultMcps: asyncNoop,
  },
  agent: {
    listDurable: async () => [],
    createDurable: asyncNoop,
    deleteDurable: asyncNoop,
    renameDurable: asyncNoop,
    updateDurable: asyncNoop,
    pickIcon: asyncNoop,
    saveIcon: asyncNoop,
    readIcon: async () => null,
    removeIcon: asyncNoop,
    reorderDurable: asyncNoop,
    getWorktreeStatus: asyncNoop,
    deleteCommitPush: asyncNoop,
    deleteCleanupBranch: asyncNoop,
    deleteSavePatch: asyncNoop,
    deleteForce: asyncNoop,
    deleteUnregister: asyncNoop,
    readQuickSummary: async () => null,
    getDurableConfig: asyncNoop,
    updateDurableConfig: asyncNoop,
    spawnAgent: asyncNoop,
    killAgent: asyncNoop,
    spawnCompanion: async () => 'companion-test',
    getCompanionStatus: async () => 'none',
    getCompanionWorkspace: async () => '/tmp/test-workspace',
    getModelOptions: async () => [],
    checkOrchestrator: async () => ({ available: true }),
    getOrchestrators: async () => [],
    getToolVerb: async () => '',
    getSummaryInstruction: async () => '',
    readTranscript: async () => null,
    isHeadlessAgent: async () => false,
    onHookEvent: () => noop,
    onAgentWaking: () => noop,
    // Structured mode
    startStructured: asyncNoop,
    cancelStructured: asyncNoop,
    sendStructuredMessage: asyncNoop,
    respondPermission: asyncNoop,
    getBackupInfo: async () => null,
    restoreFromBackup: async () => ({ restoredCount: 0, agents: [] }),
    onStructuredEvent: () => noop,
    listSessions: async () => [],
    updateSessionName: asyncNoop,
    getTranscriptInfo: asyncNoop,
    readTranscriptPage: asyncNoop,
    readSessionTranscript: async () => null,
    getSessionSummary: async () => null,
  },
  git: {
    info: asyncNoop,
    checkout: asyncNoop,
    stage: asyncNoop,
    unstage: asyncNoop,
    stageAll: asyncNoop,
    unstageAll: asyncNoop,
    discard: asyncNoop,
    commit: asyncNoop,
    push: asyncNoop,
    pull: asyncNoop,
    diff: async () => '',
    createBranch: asyncNoop,
    stash: asyncNoop,
    stashPop: asyncNoop,
    listWorktrees: async () => [],
    log: async () => [],
    showCommit: async () => ({ hash: '', files: [] }),
    commitDiff: async () => ({ original: '', modified: '' }),
  },
  agentSettings: {
    readInstructions: async () => '',
    saveInstructions: asyncNoop,
    readMcpConfig: async () => [],
    listSkills: async () => [],
    listAgentTemplates: async () => [],
    listSourceSkills: async () => [],
    listSourceAgentTemplates: async () => [],
    readSourceSkillContent: async () => '',
    writeSourceSkillContent: asyncNoop,
    deleteSourceSkill: asyncNoop,
    readSourceAgentTemplateContent: async () => '',
    writeSourceAgentTemplateContent: asyncNoop,
    deleteSourceAgentTemplate: asyncNoop,
    createSkill: asyncNoop,
    createAgentTemplate: asyncNoop,
    readPermissions: async () => ({}),
    savePermissions: asyncNoop,
    readSkillContent: async () => '',
    writeSkillContent: asyncNoop,
    deleteSkill: asyncNoop,
    readAgentTemplateContent: async () => '',
    writeAgentTemplateContent: asyncNoop,
    deleteAgentTemplate: asyncNoop,
    listAgentTemplateFiles: async () => [],
    readMcpRawJson: async () => '{"mcpServers": {}}',
    writeMcpRawJson: async () => ({ ok: true }),
    readProjectAgentDefaults: async () => ({}),
    writeProjectAgentDefaults: asyncNoop,
    resetProjectAgentDefaults: asyncNoop,
    getProjectConfigBreakdown: async () => ({
      userInstructions: '',
      pluginInstructionBlocks: [],
      allowRules: [],
      denyRules: [],
      skills: [],
      agentTemplates: [],
      mcpServers: [],
      orphanedPluginIds: [],
    }),
    removePluginInjectionItem: async () => false,
    getConventions: async () => null,
    materializeAgent: asyncNoop,
    previewMaterialization: async () => null,
    computeConfigDiff: async () => ({ agentId: '', agentName: '', hasDiffs: false, items: [] }),
    propagateConfigChanges: async () => ({ ok: true, message: '', propagatedCount: 0 }),
  },
  file: {
    readTree: async () => [],
    read: async () => '',
    readBinary: async () => '',
    write: asyncNoop,
    showInFolder: asyncNoop,
    openInEditor: asyncNoop,
    mkdir: asyncNoop,
    delete: asyncNoop,
    rename: asyncNoop,
    copy: asyncNoop,
    stat: async () => ({ size: 0, isDirectory: false, isFile: true, modifiedAt: 0 }),
    watchStart: asyncNoop,
    watchStop: asyncNoop,
    onWatchEvent: () => noop,
    offWatchEvent: noop,
    search: async () => [],
  },
  plugin: {
    discoverCommunity: async () => [],
    storageRead: async () => undefined,
    storageWrite: asyncNoop,
    storageDelete: asyncNoop,
    storageList: async () => [],
    fileRead: async () => '',
    fileWrite: asyncNoop,
    fileDelete: asyncNoop,
    fileExists: async () => false,
    fileListDir: async () => [],
    gitignoreAdd: asyncNoop,
    gitignoreRemove: asyncNoop,
    gitignoreCheck: async () => false,
    startupMarkerRead: async () => null,
    startupMarkerWrite: asyncNoop,
    startupMarkerClear: asyncNoop,
    mkdir: asyncNoop,
    uninstall: asyncNoop,
    listProjectInjections: async () => ({ skills: [], agentTemplates: [], hasInstructions: false, permissionAllowCount: 0, permissionDenyCount: 0, mcpServerNames: [] }),
    cleanupProjectInjections: asyncNoop,
    listOrphanedPluginIds: async () => [],
    registerManifest: asyncNoop,
    refreshManifestFromDisk: async () => null,
    loadModuleSource: async () => '',
  },
  marketplace: {
    fetchRegistry: async () => ({ registry: { version: 1, updated: '', plugins: [] }, featured: null }),
    installPlugin: async () => ({ success: true }),
    checkPluginUpdates: async () => [],
    updatePlugin: asyncNoop,
    getPluginUpdatesStatus: () => ({ updates: [], incompatibleUpdates: [], checking: false, lastCheck: null, updating: {}, error: null }),
    onPluginUpdatesChanged: () => noop,
    listCustomMarketplaces: async () => [],
    addCustomMarketplace: asyncNoop,
    removeCustomMarketplace: asyncNoop,
    toggleCustomMarketplace: asyncNoop,
    fetchCustomRegistries: async () => [],
  },
  log: {
    write: noop,
    getSettings: async () => ({ enabled: true, namespaces: {}, retention: 'medium', minLogLevel: 'info' }),
    saveSettings: asyncNoop,
    getNamespaces: async () => [],
    getPath: async () => '',
  },
  process: {
    exec: async () => ({ stdout: '', stderr: '', exitCode: 0 }),
  },
  pluginMcp: {
    contributeTools: asyncNoop,
    removeTools: asyncNoop,
    listTools: async () => [],
    onToolCall: () => noop,
    sendToolResult: noop,
  },
  app: {
    openExternalUrl: asyncNoop,
    getNotificationSettings: async () => ({ enabled: true }),
    saveNotificationSettings: asyncNoop,
    sendNotification: asyncNoop,
    closeNotification: asyncNoop,
    onNotificationClicked: () => noop,
    onOpenSettings: () => noop,
    onOpenAbout: () => noop,

    getTheme: async () => ({ themeId: 'catppuccin-mocha' }),
    saveTheme: asyncNoop,
    onThemeChanged: vi.fn(() => noop),
    updateTitleBarOverlay: asyncNoop,
    getOrchestratorSettings: async () => ({ enabled: ['claude-code'] }),
    saveOrchestratorSettings: asyncNoop,
    getVersion: async () => '0.0.0-test',
    isPreviewEligible: async () => false,
    getArchInfo: async () => ({ arch: 'arm64', platform: 'darwin', rosetta: false }),
    getHeadlessSettings: async () => ({ enabled: true }),
    saveHeadlessSettings: asyncNoop,
    getFreeAgentSettings: async () => ({ defaultMode: 'auto' }),
    saveFreeAgentSettings: asyncNoop,
    setDockBadge: asyncNoop,
    getBadgeSettings: async () => ({ showBadge: true }),
    saveBadgeSettings: asyncNoop,
    getUpdateSettings: async () => ({ autoUpdate: false }),
    saveUpdateSettings: asyncNoop,
    checkForUpdates: asyncNoop,
    getUpdateStatus: async () => ({ state: 'idle' }),
    applyUpdate: asyncNoop,
    getPendingReleaseNotes: async () => null,
    clearPendingReleaseNotes: asyncNoop,
    getVersionHistory: async () => [],
    getClipboardSettings: async () => ({ clipboardCompat: false }),
    saveClipboardSettings: asyncNoop,
    readClipboardImage: async () => null,
    getSessionSettings: async () => ({ promptForName: false, projectOverrides: {} }),
    saveSessionSettings: asyncNoop,
    getClubhouseModeSettings: async () => ({ enabled: false }),
    saveClubhouseModeSettings: asyncNoop,
    getSoundSettings: async () => ({ activePack: null, slotAssignments: {}, eventSettings: {}, projectOverrides: {} }),
    saveSoundSettings: asyncNoop,
    listSoundPacks: async () => [],
    importSoundPack: asyncNoop,
    deleteSoundPack: asyncNoop,
    getSoundData: async () => null,
    onUpdateStatusChanged: () => noop,
    restart: asyncNoop,
    getExperimentalSettings: async () => ({}),
    saveExperimentalSettings: asyncNoop,
    getLiveAgentsForUpdate: vi.fn().mockResolvedValue([]),
    getPendingResumes: vi.fn().mockResolvedValue(null),
    resumeManualAgent: vi.fn().mockResolvedValue(undefined),
    resolveWorkingAgent: vi.fn().mockResolvedValue(undefined),
    confirmUpdateRestart: vi.fn().mockResolvedValue(undefined),
    devSimulateUpdateRestart: vi.fn().mockResolvedValue(undefined),
    onDevSimulateUpdateRestart: vi.fn().mockReturnValue(() => {}),
    onResumeStatusUpdate: vi.fn().mockReturnValue(() => {}),
  },
  profile: {
    getSettings: async () => ({ profiles: [] }),
    saveProfile: asyncNoop,
    deleteProfile: asyncNoop,
    getProfileEnvKeys: async () => [],
  },
  annex: {
    getSettings: async () => ({ enabled: false, deviceName: '', alias: '', icon: 'computer', color: 'indigo', autoReconnect: true }),
    saveSettings: asyncNoop,
    getStatus: async () => ({ advertising: false, port: 0, pin: '', connectedCount: 0, fingerprint: '', alias: '', icon: 'computer', color: 'indigo' }),
    regeneratePin: asyncNoop,
    onStatusChanged: () => noop,
    onAgentSpawned: () => noop,
    listPeers: async () => [],
    removePeer: asyncNoop,
    removeAllPeers: asyncNoop,
    unlockPairing: asyncNoop,
    onPairingLocked: () => noop,
    onPeersChanged: () => noop,
    onLockStateChanged: () => noop,
    disconnectController: asyncNoop,
    disableAndDisconnect: asyncNoop,
    notifyPause: asyncNoop,
    purgeServerConfig: asyncNoop,
  },
  annexClient: {
    getSatellites: async () => [],
    getDiscovered: async () => [],
    pairWith: async () => ({ success: false, error: 'mock' }),
    connect: asyncNoop,
    disconnect: asyncNoop,
    retry: asyncNoop,
    scan: asyncNoop,
    ptyInput: asyncNoop,
    clipboardImage: asyncNoop,
    ptyResize: asyncNoop,
    agentSpawn: asyncNoop,
    agentKill: asyncNoop,
    agentWake: asyncNoop,
    ptyGetBuffer: vi.fn(async () => ''),
    fileTree: vi.fn(async () => []),
    fileRead: vi.fn(async () => ''),
    ptySpawnShell: asyncNoop,
    gitOperation: vi.fn(async () => ({})),
    sessionList: vi.fn(async () => []),
    sessionTranscript: vi.fn(async () => null),
    sessionSummary: vi.fn(async () => null),
    agentCreateDurable: vi.fn(async () => ({})),
    agentDeleteDurable: vi.fn(async () => ({ ok: true })),
    agentWorktreeStatus: vi.fn(async () => ({ isValid: true, branch: 'main', uncommittedFiles: [], unpushedCommits: [], hasRemote: true })),
    agentReorder: asyncNoop,
    canvasMutation: asyncNoop,
    gpGet: vi.fn(async () => ({})),
    gpUpdate: vi.fn(async () => ({})),
    gpBulletinDigest: vi.fn(async () => []),
    gpBulletinTopic: vi.fn(async () => []),
    gpBulletinAll: vi.fn(async () => []),
    gpBulletinPost: vi.fn(async () => ({})),
    gpShoulderTap: vi.fn(async () => ({})),
    gpDeleteMessage: vi.fn(async () => ({ deleted: false })),
    gpDeleteTopic: vi.fn(async () => ({ deleted: false })),
    gpSetTopicProtection: vi.fn(async () => ({ ok: true })),
    gpInjectMessage: vi.fn(async () => true),
    forgetSatellite: asyncNoop,
    forgetAllSatellites: asyncNoop,
    onSatellitesChanged: () => noop,
    onDiscoveredChanged: () => noop,
    onSatelliteEvent: () => noop,
  },
  agentQueue: {
    list: async () => [],
    create: asyncNoop,
    get: asyncNoop,
    update: asyncNoop,
    delete: async () => false,
    listTasks: async () => [],
    getTask: asyncNoop,
    onChanged: () => noop,
    onTaskChanged: () => noop,
  },
  groupProject: {
    list: async () => [],
    create: asyncNoop,
    get: asyncNoop,
    update: asyncNoop,
    delete: async () => false,
    getBulletinDigest: async () => [],
    getTopicMessages: async () => [],
    getAllMessages: async () => [],
    postBulletinMessage: asyncNoop,
    sendShoulderTap: asyncNoop,
    deleteMessage: async () => false,
    deleteTopic: async () => false,
    setTopicProtection: async () => false,
    getRetentionConfig: async () => ({ maxPerTopic: 100, maxTotal: 500 }),
    saveRetentionConfig: async () => true,
    injectMessage: async () => true,
    onChanged: () => noop,
  },
  mcpBinding: {
    getBindings: async () => [],
    bind: asyncNoop,
    unbind: asyncNoop,
    setInstructions: asyncNoop,
    setDisabledTools: asyncNoop,
    registerWebview: asyncNoop,
    unregisterWebview: asyncNoop,
    onBindingsChanged: () => noop,
    onToolActivity: () => noop,
  },
  assistant: {
    spawn: asyncNoop,
    bind: asyncNoop,
    unbind: asyncNoop,
    sendFollowup: asyncNoop,
    sendStructuredFollowup: asyncNoop,
    onResult: () => noop,
    reset: asyncNoop,
    saveHistory: asyncNoop,
    loadHistory: asyncNoop,
  },
  canvas: {
    onCommand: () => noop,
    sendCommandResult: noop,
    layoutElk: vi.fn(async () => ({ nodes: [], edges: [] })),
  },
  window: {
    createPopout: asyncNoop,
    closePopout: asyncNoop,
    listPopouts: async () => [],
    isPopout: () => false,
    getPopoutParams: () => null,
    focusMain: asyncNoop,
    onNavigateToAgent: () => noop,
    getAgentState: async () => ({ agents: {}, agentDetailedStatus: {}, agentIcons: {} }),
    onRequestAgentState: () => noop,
    respondAgentState: noop,
    broadcastAgentState: noop,
    onAgentStateChanged: () => noop,
    getHubState: async () => null,
    onRequestHubState: () => noop,
    respondHubState: noop,
    onHubStateChanged: () => noop,
    broadcastHubState: noop,
    sendHubMutation: noop,
    onHubMutation: () => noop,
    getCanvasState: async () => null,
    onRequestCanvasState: () => noop,
    respondCanvasState: noop,
    onCanvasStateChanged: () => noop,
    broadcastCanvasState: noop,
    sendCanvasMutation: noop,
    onCanvasMutation: () => noop,
    setTitle: asyncNoop,
    focusPopout: asyncNoop,
    onPopoutsChanged: () => noop,
  },
});
