import type { PluginManifest } from '../../../../shared/plugin-types';

const FOLDER_ICON = `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>`;

export const manifest: PluginManifest = {
  id: 'files',
  name: 'Files',
  version: '1.0.0',
  description: 'Project file browser with Monaco editor, markdown preview, and image display.',
  author: 'Clubhouse',
  engine: { api: 0.6 },
  scope: 'project',
  permissions: ['files', 'files.watch', 'git', 'commands', 'notifications', 'storage'],
  contributes: {
    tab: { label: 'Files', icon: FOLDER_ICON, layout: 'sidebar-content' },
    commands: [
      { id: 'refresh', title: 'Refresh File Tree', defaultBinding: 'Meta+Shift+R' },
      { id: 'search', title: 'Search Across Files', defaultBinding: 'Meta+Shift+F' },
      { id: 'close-tab', title: 'Close Active Tab', defaultBinding: 'Meta+Shift+W' },
      { id: 'reopen-tab', title: 'Reopen Last Closed Tab', defaultBinding: 'Meta+Shift+L' },
      { id: 'next-tab', title: 'Next Tab', defaultBinding: 'Meta+Shift+]' },
      { id: 'prev-tab', title: 'Previous Tab', defaultBinding: 'Meta+Shift+[' },
    ],
    settings: [
      {
        key: 'showHiddenFiles',
        type: 'boolean',
        label: 'Show hidden files',
        description: 'Display files and directories starting with a dot.',
        default: true,
      },
    ],
    help: {
      topics: [
        {
          id: 'file-browser',
          title: 'File Browser',
          content: [
            '## File Browser',
            '',
            'The Files tab provides a project file tree and built-in editor.',
            '',
            '### Supported formats',
            '- **Code files** — Syntax-highlighted editing via Monaco (40+ languages)',
            '- **Markdown** — Preview/Source toggle with syntax-highlighted code blocks',
            '- **SVG** — Preview/Source toggle',
            '- **Images** — Inline display (PNG, JPG, GIF, WebP, ICO, BMP)',
            '',
            '### Toolbar',
            '- **New File / New Folder** — Create items at the project root or selected directory',
            '- **Expand All / Collapse All** — Expand or collapse the entire file tree',
            '- **Refresh** — Manually reload the file tree',
            '',
            '### Worktree selector',
            'Use the dropdown to quickly switch between agent worktrees in `.clubhouse/agents/`.',
            '',
            '### Branch indicator',
            'The current git branch is displayed in the sidebar header.',
            '',
            '### Auto-refresh',
            'The file tree updates automatically when files change outside Clubhouse.',
            '',
            '### Tabs',
            '- **Single-click** a file in the tree to open it as a preview tab (italic title)',
            '- **Double-click** or **Enter** a file to open it as a permanent tab',
            '- Editing a preview tab automatically promotes it to permanent',
            '- Right-click a tab for options: Close, Close Others, Close All, Close to Right, Pin/Unpin, Copy Path',
            '- **Pin** a tab to keep it as an icon-only tab that cannot be accidentally closed',
            '- Drag tabs to reorder them',
            '',
            '### Keyboard shortcuts',
            '- **Cmd+S / Ctrl+S** — Save the current file',
            '- **Cmd+Shift+W** — Close active tab',
            '- **Cmd+Shift+L** — Reopen last closed tab',
            '- **Cmd+Shift+]** — Next tab',
            '- **Cmd+Shift+[** — Previous tab',
            '- **Arrow Up/Down** — Navigate the file tree',
            '- **Enter** — Open file or toggle directory',
            '- **Delete/Backspace** — Delete focused file or folder',
            '',
            '### File operations',
            'Right-click a file or folder for options: create, rename, copy, and delete.',
            '',
            '### Settings',
            '- **Show hidden files** — Toggle visibility of dotfiles in the tree (on by default).',
          ].join('\n'),
        },
      ],
    },
  },
  settingsPanel: 'declarative',
};
